name: "Label Conflicting Pull Requests"
description: "This action adds a given label to Pull Requests that have merge conflicts and removes a given label from these pull requests"
inputs:
  repoToken:
    description: "Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  dirtyLabel:
    description: "Name of the label which indicates that the branch is dirty"
    required: true
  removeOnDirtyLabel:
    description: "Name of the label which should be removed"
  retryAfter:
    description: "Number of seconds after which the action runs again if the mergable state is unknown."
  retryMax:
    description: "Number of times the action retries calculating the mergable state"
  continueOnMissingPermissions:
    description: "Boolean. Whether to continue or fail when the provided token is missing permissions. By default pull requests from a fork do not have access to secrets and get a read only github token, resulting in a failure to update tags."
  commentOnDirty:
    description: "String. Comment to add when the pull request is conflicting. Supports markdown."
  commentOnClean:
    description: "String. Comment to add when the pull request is not conflicting anymore. Supports markdown."
ouputs:
  prDirtyStatuses:
    description: "Object-map. The keys are pull request numbers and their values whether a PR is dirty or not."
runs:
  using: "node16"
  main: "dist/index.js"
author: "Sebastian Silbermann"
branding:
  icon: "activity"
  color: "black"
