name: "CI"
on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolved
  pull_request:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@master
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn
      - name: Format
        run: yarn format
      - name: Check format
        run: git diff --exit-code
      - name: Build
        run: yarn build
      - name: Checked in build?
        run: git diff --exit-code
      # tried to use https://github.community/t5/GitHub-Actions/Usage-of-expressions-and-contexts-in-uses-clause/m-p/39507/highlight/false#M3837
      # but doesn't seem to work
      - name: Test (PR)
        # Add your repository and branch here to test your changes
        # e.g. eps1lon/actions-label-merge-conflict@feat/retry-unknown
        uses: ./
        with:
          # pull_requests don't have access to secrets
          continueOnMissingPermissions: "${{ github.event.action == 'synchronize' }}"
          dirtyLabel: "PR: needs rebase"
          removeOnDirtyLabel: "PR: ready to ship"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
      - name: Test
        uses: eps1lon/actions-label-merge-conflict@main
        with:
          # pull_requests don't have access to secrets
          continueOnMissingPermissions: "${{ github.event.action == 'synchronize' }}"
          dirtyLabel: "PR: needs rebase"
          removeOnDirtyLabel: "PR: ready to ship"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
